### ISSUE TITLE
Suggestions: simplify API by passing module in graphql hooks

### ISSUE THREAD

**Issue by MargaretKrutikova** [lessp/revery-graphql-hooks#3]
The current API is very close to the one in `reason-apollo-hooks`, which looks like this:
```reason
module HelloQueryConfig = [%graphql ...];
module HelloQuery = ReasonApolloHooks.Query.Make(HelloQueryConfig);
...
let (query, _) = HelloQuery.use();
```

**UPDATE:**

> One cool feature has recently landed in graphql_ppx_re - definition with parse, query and composeVariables accessible as a tuple on MyGraphqlQuery.definition, see this PR. Maybe it is worth moving there instead of using functors/modules?

> Then it will be possible to have useQuery(MyGraphqlQuery.definition, ~variables=..., ()). And reason-urql are going in that direction, see this PR. I could look into this if you think it will be a good idea 😄

**Proposed change:**
```reason
let result = Graphql.useQuery(~variables=..., MyGraphqlQuery.definition, ());
```

------

~~It seems redundant that you need to create `HelloQuery` module for each of your queries and mutations.~~

~~One simplification could be to have `graphql` hooks as simple functions (as opposed to being created from modules) that accept `HelloQueryConfig` module and extract `parse` and `t` from it. Then it could look like this:~~
```reason
[redacted]
```

~~This is possible due to first-class modules in `OCaml`. This [PR](https://github.com/Astrocoders/reason-apollo-hooks/pull/59) in `reason-apollo-hooks` introduces this change.~~

This is just a suggestion, would love to hear your opinion about it 😄

**Comment by lessp** [comment]
Thanks a lot for sharing your thoughts, @MargaretKrutikova, very interesting!

It's a bit unfortunate that the first class-module syntax is a bit awkward, would be nice if we could do:
```ocaml
Graphql.Query.use(HelloQuery, ~variables=..., ())
```

I feel that both approaches have their advantages and disadvantages from an API-standpoint, with the first-class module approach it may be easier to remember (and refactor perhaps) that the `Graphql.QueryType.use` is always the one you call, and pass whatever query you have constructed.

The disadvantage, as hinted at previously, would be the slightly awkward syntax. While the functor-approach, though having to do more boilerplate stays out of your way when you're calling the actual hooks!

Perhaps an idea would be (unless you'd like to experiment a bit with this in a separate branch of course 😄), to wait for the changes to land in `reason-apollo-hooks` and make a decision based on how that feels!

**Comment by fakenickels** [comment]
I'm not an expert in OCaml's compiler intricacies but I have heard that in native OCaml first-class modules come with a bit of a performance cost because the compiler can't do optimizations in compile time because it can't infer what kinds of modules will be used as an argument. While with functors it is more capable of doing that because it knows in compile time all that is gonna happen. In JS we don't have such a problem because in the end all will be compiled down to JS objects, so we are fine here.

If someone with more knowledge about those could join in the discussion would be amazing 🙏

**Comment by MargaretKrutikova** [comment]
One cool feature has recently landed in `graphql_ppx_re` - definition with `parse`, `query` and `composeVariables` accessible as a tuple on `MyGraphqlQuery.definition`, see [this PR](https://github.com/baransu/graphql_ppx_re/pull/48). Maybe it is worth moving there instead of using functors/modules? 

Then it will be possible to have `useQuery(MyGraphqlQuery.definition, ~variables=..., ())`. And `reason-urql` are going in that direction, see [this PR](https://github.com/FormidableLabs/reason-urql/pull/132). I could look into this if you think it will be a good idea 😄

**Comment by lessp** [comment]
> One cool feature has recently landed in `graphql_ppx_re` - definition with `parse`, `query` and `composeVariables` accessible as a tuple on `MyGraphqlQuery.definition`, see [this PR](https://github.com/baransu/graphql_ppx_re/pull/48). Maybe it is worth moving there instead of using functors/modules?
> 
> Then it will be possible to have `useQuery(MyGraphqlQuery.definition, ~variables=..., ())`. And `reason-urql` are going in that direction, see [this PR](https://github.com/FormidableLabs/reason-urql/pull/132). I could look into this if you think it will be a good idea 😄

Cool! That does indeed look pretty sweet! I noticed that the PR for `graphql_ppx` didn't include changes for native, so that would need to be added as well!

**Comment by lessp** [comment]
I have (I think) implemented what's needed in `graphql_ppx` for native as well. PR here: https://github.com/baransu/graphql_ppx_re/pull/57

Though, it looks like there's currently an issue with fetch in the examples repo which would make it hard to test local changes, hoping to get that resolved sooner than later!

**Comment by lessp** [comment]
I have sorted out the dependencies for local development if you'd like to give it a spin @MargaretKrutikova:

<https://github.com/lessp/revery-graphql-hooks/tree/refactor/simplify-api>

**Comment by lessp** [comment]
@all-contributors please add @MargaretKrutikova for ideas
